// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyDs5_AmZN7GagAUrASTposb3lduNPWI-_I',
    appId: '1:419925464646:web:c502afcf6b253bdc8b5c47',
    messagingSenderId: '419925464646',
    projectId: 'chris101-zj0evi',
    authDomain: 'chris101-zj0evi.firebaseapp.com',
    storageBucket: 'chris101-zj0evi.appspot.com',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyA0I7GuE9LbUALi0HgGQ5_-1u0PElvYy9U',
    appId: '1:419925464646:android:471a286ae78cad8f8b5c47',
    messagingSenderId: '419925464646',
    projectId: 'chris101-zj0evi',
    storageBucket: 'chris101-zj0evi.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyDxM2wol3YbtSFQyO8CM9SmlE1TQju5e6w',
    appId: '1:419925464646:ios:88cea70038db577c8b5c47',
    messagingSenderId: '419925464646',
    projectId: 'chris101-zj0evi',
    storageBucket: 'chris101-zj0evi.appspot.com',
    iosClientId: '419925464646-0tv0515pou2firlsgukki90ffra5b6g4.apps.googleusercontent.com',
    iosBundleId: 'com.example.sacco',
  );

}